# -*- coding: utf-8 -*-
"""data and table .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPoYCchi6xP-tUU64Dm1JdxwF7H6ed8N
"""

from google.colab import data_table
data_table.enable_dataframe_formatter()

from google.colab import data_table
data_table.disable_dataframe_formatter()

from google.colab import data_table
from vega_datasets import data

data_table.enable_dataframe_formatter()

data.airports()

from google.colab import data_table
data_table.disable_dataframe_formatter()

data.airports()

from google.colab import data_table
data_table.DataTable(data.airports(), include_index=False, num_rows_per_page=10)



